### ISSUE TITLE
Integrating in existing projects

### ISSUE THREAD

**Issue by IwanKaramazow** [reasonml/rehydrate#14]
Before we reach the `tweet about this`-phase, we should provide a way to easily integrate this into existing projects. I'm now manually copying files, which does pretty much not scale at all.
The approach I'm going to follow now is dumping all output into one flat folder, which I'm going to alias through webpack for easy access.

Thoughts?

**Comment by chenglou** [comment]
Can you describe a bit more the problem you're having? Is it the `require`s?

**Comment by jordwalke** [comment]
So, the typical way of integrating things into web development projects is via `npm`. So, you probably want to be able to include Rehydrate as an npm dependency, and then be able to compile some project's `.re` components using BuckleScript, right?

**Comment by IwanKaramazow** [comment]
Yes, that's what I was referring to.
When integrating this with an existing project, I want to `npm install rehydrate` as a newcomer.
Hell, a webpack loader isn't probably a bad idea at this stage.

**Comment by chenglou** [comment]
rehydrate currently works as an npm dependency, albeit with some friction. As a matter of fact it depends on [reason-js]https://github.com/reasonml/rehydrate/blob/7b57515c6628019b4c93a21e1e72410ef548dd18/bsconfig.json#L12). Is this what you mean?

**Comment by IwanKaramazow** [comment]
That's what I mean.

**Comment by chenglou** [comment]
Christ, just realized I have npm ignored bsconfig so using rehydrate as a dependency failed. Ugh. Credit to @chandu0101 for finding this the hard way.

Next up is to verify that transitive deps work well, likewise for diamon-shaped dependencies, e.g. another project also uses reason-js (which rehydrate uses)

**Comment by chenglou** [comment]
Done by https://github.com/chenglou/rehydrate-example

For in-depth integration, like guideline on whether one should be putting js source files alongside bs js artifacts, we can do that later.
