### ISSUE TITLE
Do not require user to call `createClass`

### ISSUE THREAD

**Issue by jordwalke** [reasonml/rehydrate#3]
This can be done in the component base somehow.

**Comment by IwanKaramazow** [comment]
I think we're _under_ -using functors with the current api, I'm all in favor for skipping `createClass` & hooking things straight onto `React.Component.prototype`.

**Comment by chenglou** [comment]
btw, we're exposing the backing class through `comp`. This is needed if js calls us. `let foo = require('foo').comp; <foo />`.

**Comment by chenglou** [comment]
solved
