### ISSUE TITLE
Missing props on createElement

### ISSUE THREAD

**Issue by glennsl** [reasonml/rehydrate#32]
I haven't gone through [the list](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes) but noticed that the global attribute "title" is missing as a prop on createElement. Is there a reason (hah!) for this, or can I just add them?

**Comment by chenglou** [comment]
Add them! Could you also add a comment that says "this list isn't exhaustive, we'll add more as we go" please?
