### ISSUE TITLE
Support data-* and aria-* attributes

### ISSUE THREAD

**Issue by glennsl** [reasonml/rehydrate#33]
Right now, it's not even considered valid syntax by the JSX ppx.

See:
https://github.com/facebook/react/blob/b59fb796ea2c05c8609858fc28b707d13245fd9c/docs/docs/reference-dom-elements.md#all-supported-html-attributes

**Comment by chrislf** [comment]
Is there a way to do this without extending the JSX ppx? It is not clear to me where the code to add the attributes would go. I'm willing to give this a shot if people could point me to areas to start or example commits.

**Comment by chrislf** [comment]
Please ignore my last comment: I missed the bit in the documentation about how to do this: https://reasonml.github.io/reason-react/docs/en/invalid-prop-name.html#docsNav

**Comment by gabrielseco** [comment]
Hi @chrislf could you edit the invalid-prop-name url with [https://reasonml.github.io/reason-react/docs/en/invalid-prop-name.html#docsNav](url) to redirect people to the new link. 

Thanks

**Comment by yawaramin** [comment]
There was some discussion recently that we could desugar `<foo bar'baz="quux">` to `<foo bar-baz="quux">` or rather, `createElement('foo', {'bar-baz': 'quux'})`

The reasoning was that apostrophe is not valid in an HTML attribute anyway so there's no chance of a clash here, and thus no reason anyone would want to use apostrophe in JSX attributes.
