### ISSUE TITLE
updater should call handler using state provided by setState callback

### ISSUE THREAD

**Issue by istarkov** [reasonml/rehydrate#37]
For now the problem is that `callback` receives [component instance state](
https://github.com/reasonml/rehydrate/blob/6808bf1a19e701214e4456967b4aab155d79802c/src/reactRe.re#L438)
and not the `state` provided by `setState((prevState, props) =>  ...)` callback arguments.

This can cause situations when handler can get outdated version of state.
The simples example to reproduce just call event handler twice inside `setTimeout`

```javascript
// js
class Tmp extends Component {
  componentDidMount() {
      setTimeout(() => {
         this.props.onIncreaseCounter();
         this.props.onIncreaseCounter();
      }, 100);
  }
  ...
}
```

So using such component in reason using `updater` will update counter just once

```ocaml
let increaseCounter {state} event => Some {...state, counter: state.counter + 1 }
let render {updater} => {
   <Tmp onIncreaseCounter=(updater increaseCounter) />
}
```

For now seems like this problem is unsolvable.

as jordwalke said:

> there's a problem in react right now that prevents us from actually using it.
> Because if you use the callback version of setState, (in React) there's no opportunity for you to say "nevermind don't update state" after you examine the freshest state
> I reported the issue to team mates

So until we get additional `setState` version in React, all will be as is.

**Comment by chenglou** [comment]
This has been fixed for a while now in https://github.com/reasonml/reason-react, thanks!
