### ISSUE TITLE
Bypass createClass

### ISSUE THREAD

**Issue by chenglou** [reasonml/rehydrate#40]
createClass will be moved out of React core. We don't currently compile to es6 classes (the spec isn't even finalized), so we can take this occasion to also drop our internal usage of createClass, and wire things up into React ourselves. Page initialization cost should go down a bit.

**Comment by slonoed** [comment]
Hi! React remove createClass in version 16. Do you have plans on this ticket? There is `create-react-class` that provide migration. Maybe it can be used.
I want to help with this, but I don't know your plans.

**Comment by chenglou** [comment]
We'll simply wire things up under the hood by looking at how es6 classes work. cc @IwanKaramazow. It might only be a few lines change.

**Comment by aweary** [comment]
Would it be worth using `create-react-class` for now until ES6 classes are wired up? Currently, new projects using reason-react will get the deprecation warning introduced in 15.5, without a way to get rid of it.

**Comment by xtuc** [comment]
I'm new to reasonml :wave: and would like to get this done.

What should we do with the additional dependency (create-react-class)?

- It could be a peerDep as with React and React-dom ([package.json#L22-L23](https://github.com/reasonml/reason-react/blob/master/package.json#L22-L23)) but all React app won't have create-react-class as dep.

- Or should I add it to devDeps?

**Comment by rt2zz** [comment]
imo it should be a regular dependency

**Comment by chenglou** [comment]
Fixed in https://github.com/reasonml/reason-react
