### ISSUE TITLE
Non-ascii characters not displaying correctly

### ISSUE THREAD

**Issue by sgrove** [reasonml/rehydrate#42]
Not sure what the root cause is, but noticed that
`<span>(ReactRe.stringToElement "한국어")</span>`
Is rendered as
`<span>íêµ&shy;ì´</span>`

**Comment by chenglou** [comment]
Sorry I meant opening an issue in Reason. Like, just `"한국어"`

I get `"\237\149\156\234\181\173\236\150\180"`?

**Comment by bobzhang** [comment]
It might be an issue on our side, we will fix it in next release, there is a work around [%raw {|"한국어"|} ]
But besides encoding issue, I guess refmt would come across same issues when formatting

**Comment by typeofweb** [comment]
There's a way to overcome this issue by using BucketScript's unicode extension: http://bucklescript.github.io/bucklescript/Manual.html#_bucklescript_annotations_for_unicode_and_js_ffi_support

Instead of
```<span>(ReactRe.stringToElement "한국어")</span>```
try
```<span>(ReactRe.stringToElement {js|한국어|js})</span>```

**Comment by chenglou** [comment]
Yep. Fixed on BS side. Now just needs refmt to pick up its game.
Thanks, closing!
