### ISSUE TITLE
type style obj

### ISSUE THREAD

**Issue by chenglou** [reasonml/rehydrate#43]
We can use the [@bs.obj] external.

**Comment by glennsl** [comment]
I'll do it!

But there ought to be a way of accessing and manipulating these too. I'm thinking a `Style` module with functions to do so, like `combine` to mush them together. What do you think?

**Comment by glennsl** [comment]
Already have all the CSS2 Props implemented here:
https://github.com/glennsl/reason-tools/blob/toggle-convert/src/extension/inline/Transition.re#L3
