### ISSUE TITLE
reactRef should be a DOM element, or castable to a DOM element

### ISSUE THREAD

**Issue by glennsl** [reasonml/rehydrate#44]
Isn't it always a DOM element anyway?

**Comment by chenglou** [comment]
no, it'd be the component itself, unless the ref's directly on a react Dom element =/

**Comment by glennsl** [comment]
Right, then maybe the ref type should encapsulate that information. elements and proper components are already instantiated in different ways, so shouldn't be too hard to have them use different types, right? GADTs to the rescue, maybe? lol

**Comment by glennsl** [comment]
Found `findDOMNode` eventually... should be properly typed and documented though

**Comment by chenglou** [comment]
Sorry I was dumb. It is always a DOM element for DOM element refs, and always a component ref for component elements.
