### ISSUE TITLE
updater for stateless components

### ISSUE THREAD

**Issue by kutagh** [reasonml/rehydrate#57]
At the moment, ReactRe.Component exposes the ```updater``` wrapper, to give an up-to-date component bag to the callback (and memoize the callback) and to appropriately handle state changes from callbacks.

There is a wish for a simplified version of this wrapper for in stateless components, that only provides the props and expects an unit return value (and as such, will not do any state updates). Taking the current rehydrate docs for ```updater``` as a sample (and a temporary name of handler), we could use it like this:

```
/* `props` is up-to-date here, even though onClick is asynchronously triggered */
let handleClick props event => {Js.log "clicked!"};
let render {props, updater} => <div onClick=(handler handleClick) />
```

**Comment by chenglou** [comment]
Solved by 41019558ca8108b90eb817b7d7dff322a8b268b4!
