### ISSUE TITLE
react native support

### ISSUE THREAD

**Issue by chenglou** [reasonml/rehydrate#60]
TODO: https://gist.github.com/ckknight/e4fb973201d82d4b3d049aa4de037c76

From @ckknight. We'll make this official

**Comment by szymonzmyslony** [comment]
I will have a shot at it.

**Comment by saschatimme** [comment]
Bindings are worked on in a separate repo: https://github.com/BuckleTypes/bs-react-native

**Comment by jordwalke** [comment]
Very excited about the bindings, @saschatimme! Let us know when it's a good time to advertise them.

**Comment by chenglou** [comment]
=D
