### ISSUE TITLE
Unable to use dangerouslySetInnerHTML attribute

### ISSUE THREAD

**Issue by wyze** [reasonml/rehydrate#75]
When trying to set the attribute in the following example, it throws a type error:

```jsx
<button dangerouslySetInnerHTML={ "__html": "&times;" } />
```

Error:

```
Error: This expression has type < __html : string > Js.t
       but an expression was expected of type string
```

If this is a bug and should work, I would love to do the PR for it if I could get pointed in the right direction.

**Comment by glennsl** [comment]
The code that needs changing is just this line: https://github.com/reasonml/reason-react/blob/master/src/reactDOMRe.re#L524

The question is, what do we change the type to. Just `{. __html: string }`? @chenglou?

**Comment by wyze** [comment]
Somehow it didn't come up in GitHub search UI.

According to the docs, https://facebook.github.io/react/docs/dom-elements.html#dangerouslysetinnerhtml, it allows any object that contains a `__html` key.
