### ISSUE TITLE
Generic Style

### ISSUE THREAD

**Issue by saschatimme** [reasonml/rehydrate#79]
Reason React currently defines `style` in `ReactDOMRe`. In `bs-react-native` we have also defined styles.

Now we have a problem if some component is cross-platform (e.g. `react-navigation`) and takes `style` as a prop (for which `style` would you write the bindings?).

I would propose to move the `style` type from `ReactDOMRe` to `ReactRe`. Then we could use the same `style` in both projects.

**Comment by chenglou** [comment]
Humm, though at the native side the style prop is much smaller, right? It'd mistakenly work on native. Should we have a special ReactRe.CrossPlatformStyle.make (or something like that) instead?

(Btw, continuing the conversation at https://github.com/reasonml/reason-react/issues/11)
